version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9400:9200"
      - "9300:9300"
    networks:
      - app-network
    volumes:
      - esdata:/usr/share/elasticsearch/data
volumes:
  esdata:
    driver: local

networks:
  app-network:
    driver: bridge
